version: "3.9"

services:
  app:
    build: .
    container_name: todo-app
    restart: always

  prod:
    build: .
    container_name: todo-app-prod
    restart: always
    ports:
      - "8080:3000"
    command: pnpm start